import { createServerFn } from "@tanstack/react-start";
import { getRequestHeader } from "@tanstack/react-start/server";
import { z } from "zod";
const input = z.object({ guildId: z.string().regex(/^\d{5,25}$/), channelId: z.string().regex(/^\d{5,25}$/) });
const messageInput = input.extend({ message: z.string().min(1).max(2000) });
async function authorize(guildId: string) { const { sessionFromHeader, assertGuildAccess } = await import("@/lib/discord.server"); const session = await sessionFromHeader(getRequestHeader("cookie") ?? null); if (!session) throw new Error("Please sign in with Discord."); const guild = await assertGuildAccess(session, guildId); const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); return { session, guild, supabaseAdmin }; }
async function send(channelId: string, payload: unknown) { const token = process.env.DISCORD_TOKEN; if (!token) throw new Error("Bot delivery is not configured."); const res = await fetch(`https://discord.com/api/v10/channels/${channelId}/messages`, { method: "POST", headers: { authorization: `Bot ${token}`, "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!res.ok) throw new Error(`Discord delivery failed (${res.status}).`); return res.json(); }
export const testSend = createServerFn({ method: "POST" }).inputValidator((d: unknown) => messageInput.parse(d)).handler(async ({ data }) => { const { session, supabaseAdmin } = await authorize(data.guildId); await send(data.channelId, { embeds: [{ title: "!HOY BOT · Test Message", description: data.message, color: 0x1FB6A6, footer: { text: "Test delivery · !HOY BOT ⚓" } }] }); await supabaseAdmin.from("dashboard_access_log").insert({ discord_user_id: session.userId, discord_username: session.username, guild_id: data.guildId, action: "test:send" }); return { ok: true }; });
export const testWelcome = createServerFn({ method: "POST" }).inputValidator((d: unknown) => input.parse(d)).handler(async ({ data }) => { const { session, supabaseAdmin } = await authorize(data.guildId); await send(data.channelId, { embeds: [{ title: "WELCOME TO THE CREW! ⚓", description: "Ahoy, @Test Crew Member!\n\nThis is a live preview of your configured welcomer presentation.", color: 0xE0B15C, fields: [{ name: "Server", value: "Your Discord server", inline: true }, { name: "Member", value: "@Test Crew Member", inline: true }], footer: { text: "!HOY BOT · Cinematic Welcome Test ⚓" } }] }); await supabaseAdmin.from("dashboard_access_log").insert({ discord_user_id: session.userId, discord_username: session.username, guild_id: data.guildId, action: "test:welcome" }); return { ok: true }; });
export const testXp = createServerFn({ method: "POST" }).inputValidator((d: unknown) => input.parse(d)).handler(async ({ data }) => { const { session, supabaseAdmin } = await authorize(data.guildId); await send(data.channelId, { embeds: [{ title: "⚓ LEVEL UP · 42", description: "Ahoy, @Test Crew Member! You reached the next level.\n\n`████████████████████░░░░`\n**1,240 / 1,500 XP** to the next level.", color: 0xE0B15C, fields: [{ name: "Crew rank", value: "**#7**", inline: true }, { name: "Total XP", value: "**8,240**", inline: true }], footer: { text: "!HOY BOT · Cinematic Glassmorphism Level Card ⚓" } }] }); await supabaseAdmin.from("dashboard_access_log").insert({ discord_user_id: session.userId, discord_username: session.username, guild_id: data.guildId, action: "test:xp" }); return { ok: true }; });
