import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Trash2, RefreshCw, MessageSquareWarning } from "lucide-react";
import { getAllErrorLogs, updateErrorStatus, deleteErrorLog } from "@/lib/error-log.functions";
import { SupportReportsPanel } from "./support-reports-panel";
import { Button } from "@/components/ui/button";

function explain(entry: any) {
  const type = String(entry.error_type || "UnknownError");
  if (type === "CommandNotFound") return `Discord received a prefix command that !HOY BOT does not have registered. In this case, the message started with an unknown command (for example, “you”). This usually means a user typed ordinary text that matched the bot prefix, or the command has not been registered/synced.`;
  if (type.includes("MissingPermissions")) return "The bot or invoking member did not have the Discord permission required by this command.";
  if (type.includes("NotFound")) return "The requested Discord resource could not be found. Check the channel, message, role or server reference in the context below.";
  if (type.includes("HTTPException")) return "Discord rejected an API request. The traceback and command context below identify the operation that failed.";
  return "The bot captured an exception while processing the recorded source. Review the command, guild, channel, context and traceback to identify the failing operation.";
}

export function ErrorFeedbackPanel() {
  const qc = useQueryClient(); const q = useQuery({ queryKey: ["all-error-logs"], queryFn: getAllErrorLogs, refetchInterval: 10000 });
  const status = useMutation({ mutationFn: updateErrorStatus, onSuccess: () => qc.invalidateQueries({ queryKey: ["all-error-logs"] }) });
  const del = useMutation({ mutationFn: deleteErrorLog, onSuccess: () => qc.invalidateQueries({ queryKey: ["all-error-logs"] }) });
  return <div className="space-y-6"><section className="rounded-3xl border border-red-400/15 bg-red-400/[0.035] p-5 backdrop-blur-xl"><div className="flex items-start gap-3"><span className="flex size-11 items-center justify-center rounded-2xl border border-red-400/20 bg-red-400/10 text-red-300"><AlertTriangle className="size-5" /></span><div><p className="text-[9px] font-bold uppercase tracking-[.25em] text-red-300">ALL ERROR LOGS</p><h2 className="mt-1 text-2xl font-black">Error & Feedback Center</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Every captured bot error is classified with its source, likely cause, location, context and traceback. Mark issues fixed or leave them pending while you investigate.</p></div></div></section>
    <div className="flex items-center justify-between gap-3"><h3 className="font-bold">Bot errors</h3><Button variant="outline" size="sm" onClick={() => void q.refetch()} className="gap-2"><RefreshCw className="size-4" />Refresh</Button></div>
    <div className="space-y-3">{q.data?.map((e: any) => <details key={e.id} className={`rounded-3xl border p-5 backdrop-blur-xl ${e.status === "fixed" ? "border-emerald-400/15 bg-emerald-400/[0.025]" : "border-red-400/15 bg-white/[0.025]"}`}><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-white/10 px-2 py-1 text-[9px] uppercase tracking-wider text-white/50">{e.source || "unknown source"}</span><span className="font-mono text-sm text-red-200">{e.error_type}</span><span className="text-sm text-white/65">{e.message}</span></div><p className="mt-2 text-xs text-white/35">{e.command ? `Command: /${e.command} · ` : ""}{e.guild_id ? `Server: ${e.guild_id} · ` : ""}{new Date(e.created_at).toLocaleString()}</p></div><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider ${e.status === "fixed" ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-300"}`}>{e.status || "pending"}</span></div></summary><div className="mt-5 space-y-3"><div className="rounded-2xl border border-amber-400/10 bg-amber-400/[0.035] p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-amber-300">Likely cause</p><p className="mt-1 text-sm leading-6 text-white/70">{e.cause || explain(e)}</p></div><div className="grid gap-3 sm:grid-cols-3"><Info label="Source" value={e.source || "Unknown"} /><Info label="Location" value={e.location || e.command || "Runtime / event handler"} /><Info label="Context" value={e.context || `Guild ${e.guild_id || "N/A"}${e.channel_id ? ` · Channel ${e.channel_id}` : ""}${e.user_id ? ` · User ${e.user_id}` : ""}`} /></div>{e.traceback ? <div><p className="mb-1 text-[9px] font-bold uppercase tracking-wider text-white/35">Technical traceback</p><pre className="max-h-72 overflow-auto rounded-2xl border border-white/[0.08] bg-black/40 p-4 text-xs leading-5 text-red-100/70">{e.traceback}</pre></div> : null}<div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => status.mutate({ data: { id: e.id, status: "fixed" } })} className="gap-2"><CheckCircle2 className="size-4" />Fixed</Button><Button size="sm" variant="outline" onClick={() => status.mutate({ data: { id: e.id, status: "pending" } })}>Pending fix</Button><Button size="sm" variant="outline" className="text-red-300" onClick={() => { if (confirm("Delete this error log?")) del.mutate({ data: { id: e.id } }); }}><Trash2 className="size-4" /></Button></div></div></details>)}{!q.isLoading && !q.data?.length ? <div className="rounded-3xl border border-dashed border-white/10 p-10 text-center text-sm text-muted-foreground">No bot errors have been captured.</div> : null}</div>
    <section className="pt-2"><div className="mb-4 flex items-center gap-2"><MessageSquareWarning className="size-5 text-primary" /><h3 className="font-bold">User feedback & complaints</h3></div><SupportReportsPanel /></section>
  </div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/[0.08] bg-black/15 p-3"><p className="text-[9px] uppercase tracking-wider text-white/30">{label}</p><p className="mt-1 break-words text-xs text-white/60">{value}</p></div>; }