import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Crown, ShieldPlus, UserMinus, ArrowRight, Bug, MessageSquareWarning } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link } from "@tanstack/react-router";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { listAdmins, setAdmin } from "@/lib/admin.functions";
import { ErrorFeedbackPanel } from "./error-feedback-panel";
import { SupportReportsPanel } from "./support-reports-panel";

export function StaffPanel({ canEdit }: { canEdit: boolean }) {
  const queryClient = useQueryClient(); const [userId, setUserId] = useState(""); const [role, setRole] = useState<"admin"|"owner">("admin"); const [tool, setTool] = useState<"none"|"errors"|"reports">("none");
  const { data } = useQuery({ queryKey: ["admin", "staff"], queryFn: () => listAdmins() });
  const mutation = useMutation({ mutationFn: (input: { userId: string; role: "admin"|"owner"|null }) => setAdmin({ data: input }), onSuccess: () => { toast.success("Staff updated"); setUserId(""); void queryClient.invalidateQueries({ queryKey: ["admin", "staff"] }); }, onError: (error: Error) => toast.error(error.message) });
  return <div className="space-y-6">
    {canEdit ? <section className="rounded-2xl border border-[#e7a927]/35 bg-[#061321]/90 p-5 shadow-[0_15px_50px_rgba(0,0,0,0.2)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-start gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl border border-[#e7a927]/30 bg-[#e7a927]/10 text-[#ffd15a]"><Crown className="size-5" aria-hidden="true" /></div><div className="min-w-0"><h3 className="text-base font-semibold text-white">Premium Access Requests</h3><p className="mt-1 text-sm text-white/50">Review members who requested Premium access and approve or decline their unlock request.</p></div></div><Button asChild className="shrink-0 gap-2" aria-label="Open Premium Access Requests"><a href="/owner-console/plan-requests">Open Premium Requests <ArrowRight className="size-4" aria-hidden="true" /></a></Button></div></section> : null}
    <section className="rounded-3xl border border-red-400/15 bg-white/[0.025] p-4 backdrop-blur-xl"><div className="mb-3"><p className="text-[9px] font-bold uppercase tracking-[.25em] text-red-300">Owner diagnostics</p><h3 className="mt-1 text-lg font-black">ERROR & FEEDBACK</h3><p className="mt-1 text-xs text-white/40">Centralized bot errors and live user concerns.</p></div><div className="grid gap-2 sm:grid-cols-2"><Button type="button" variant={tool === "errors" ? "default" : "outline"} onClick={() => setTool(tool === "errors" ? "none" : "errors")} className="justify-start gap-2"><Bug className="size-4" />ALL ERROR LOGS</Button><Button type="button" variant={tool === "reports" ? "default" : "outline"} onClick={() => setTool(tool === "reports" ? "none" : "reports")} className="justify-start gap-2"><MessageSquareWarning className="size-4" />USERS REPORT</Button></div></section>
    {tool === "errors" ? <ErrorFeedbackPanel /> : null}{tool === "reports" ? <SupportReportsPanel /> : null}
    <div className="grid gap-6 lg:grid-cols-2"><section className="glass space-y-3 rounded-2xl p-5"><h3 className="text-lg font-semibold">Platform staff</h3>{(data?.owners ?? []).map((id) => <div key={id} className="hairline flex items-center justify-between rounded-xl px-3 py-2"><span className="font-mono text-sm">{id}</span><Badge><Crown className="mr-1 size-3" /> owner</Badge></div>)}{(data?.staff ?? []).map((member) => <div key={member.discord_user_id} className="hairline flex items-center justify-between rounded-xl px-3 py-2"><div><p className="text-sm">{member.username ?? member.discord_user_id}</p><p className="font-mono text-xs text-muted-foreground">{member.discord_user_id}</p></div><div className="flex items-center gap-2"><Badge variant="secondary">{member.role}</Badge>{canEdit ? <Button size="icon" variant="ghost" aria-label={`Remove ${member.username ?? member.discord_user_id} from staff`} onClick={() => mutation.mutate({ userId: member.discord_user_id, role: null })}><UserMinus className="size-4" aria-hidden="true" /></Button> : null}</div></div>)}</section><section className="glass space-y-3 rounded-2xl p-5"><h3 className="flex items-center gap-2 text-lg font-semibold"><ShieldPlus className="size-4" aria-hidden="true" /> Grant panel access</h3><p className="text-xs text-muted-foreground">Only owners can change staff. Admins can manage users and send notifications.</p><div className="space-y-2"><Label htmlFor="staff-id">Discord user id</Label><Input id="staff-id" value={userId} placeholder="123456789012345678" onChange={(event) => setUserId(event.target.value)} /></div><div className="flex gap-2">{(["admin","owner"] as const).map((option) => <Button key={option} size="sm" variant={role === option ? "default" : "outline"} aria-pressed={role === option} onClick={() => setRole(option)}>{option}</Button>)}</div><Button className="w-full" disabled={!canEdit || !/^\d{5,25}$/.test(userId) || mutation.isPending} onClick={() => mutation.mutate({ userId, role })}>Add staff member</Button></section></div>
  </div>;
}