import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, MessageSquareReply, Clock3 } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { getAllSupportReports, replyToSupportReport, updateSupportStatus } from "@/lib/support.functions";

export function SupportReportsPanel() {
  const qc = useQueryClient();
  const [replies, setReplies] = useState<Record<string,string>>({});
  const q = useQuery({ queryKey: ["admin-support-reports"], queryFn: getAllSupportReports, refetchInterval: 8000 });
  const reply = useMutation({ mutationFn: (v: { id: string; text: string }) => replyToSupportReport({ data: { id: v.id, reply: v.text, status: "in_progress" } }), onSuccess: () => qc.invalidateQueries({ queryKey: ["admin-support-reports"] }) });
  const status = useMutation({ mutationFn: (v: { id: string; status: "open"|"in_progress"|"resolved"|"closed" }) => updateSupportStatus({ data: v }), onSuccess: () => qc.invalidateQueries({ queryKey: ["admin-support-reports"] }) });
  return <div className="space-y-4"><div className="rounded-3xl border border-primary/15 bg-primary/[0.04] p-5 backdrop-blur-xl"><p className="text-[9px] font-bold uppercase tracking-[.25em] text-primary">User Reports</p><h2 className="mt-1 text-2xl font-black">Support & complaints</h2><p className="mt-2 text-sm text-muted-foreground">Live user concerns, bug reports and complaints. Reply directly from the Owner Console.</p></div>{q.isLoading ? <p className="text-sm text-muted-foreground">Loading reports…</p> : null}{q.data?.map((r: any) => <article key={r.id} className="rounded-3xl border border-white/[0.1] bg-white/[0.035] p-5 shadow-xl backdrop-blur-xl"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{r.subject}</h3><span className="rounded-full border border-white/10 px-2 py-1 text-[9px] uppercase tracking-wider text-white/50">{r.category}</span><span className="rounded-full border border-primary/20 px-2 py-1 text-[9px] uppercase tracking-wider text-primary">{r.priority}</span></div><p className="mt-1 text-xs text-white/40">{r.display_name || r.username || r.user_id} · {new Date(r.created_at).toLocaleString()}</p></div><span className="flex items-center gap-1 text-xs text-white/40"><Clock3 className="size-3" />{r.status}</span></div><p className="mt-4 whitespace-pre-wrap rounded-2xl border border-white/[0.07] bg-black/15 p-4 text-sm leading-6 text-white/75">{r.message}</p>{r.admin_reply ? <div className="mt-3 rounded-2xl border border-emerald-400/15 bg-emerald-400/[0.04] p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-emerald-300">Current reply</p><p className="mt-1 whitespace-pre-wrap text-sm text-white/70">{r.admin_reply}</p></div> : null}<Textarea aria-label={`Reply to ${r.subject}`} value={replies[r.id] ?? ""} onChange={(e) => setReplies((x) => ({ ...x, [r.id]: e.target.value }))} placeholder="Write a reply…" className="mt-3 min-h-24" /><div className="mt-3 flex flex-wrap gap-2"><Button disabled={!replies[r.id]?.trim() || reply.isPending} onClick={() => reply.mutate({ id: r.id, text: replies[r.id] })} className="gap-2"><MessageSquareReply className="size-4" />Reply</Button><Button variant="outline" onClick={() => status.mutate({ id: r.id, status: "in_progress" })}>Pending</Button><Button variant="outline" onClick={() => status.mutate({ id: r.id, status: "resolved" })} className="gap-2"><CheckCircle2 className="size-4" />Resolved</Button></div></article>)}{!q.isLoading && !q.data?.length ? <div className="rounded-3xl border border-dashed border-white/10 p-10 text-center text-sm text-muted-foreground">No user reports yet.</div> : null}</div>;
}