import { createFileRoute, Link } from "@tanstack/react-router";
import { Activity, ArrowRight, BarChart3, Bot, CalendarDays, FileText, Gauge, MessageSquare, Server, Shield, ShieldAlert, Sparkles, Ticket, Users } from "lucide-react";

import { useGuild } from "@/components/dashboard/guild-context";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

export const Route = createFileRoute("/dashboard/$guildId/")({
  head: () => ({ meta: [{ title: "Server Dashboard — !HOY BOT" }, { name: "description", content: "Premium !HOY BOT server command center." }] }),
  component: GuildHome,
});

const QUICK = [
  { title: "Moderation", body: "Cases, warnings, bans, kicks and timeouts.", to: "/dashboard/$guildId/moderation", cta: "Open moderation", icon: Shield },
  { title: "Auto moderation", body: "Spam, links, invites and mention protection.", to: "/dashboard/$guildId/automod", cta: "Configure AutoMod", icon: ShieldAlert },
  { title: "Command library", body: "Permissions, availability and command controls.", to: "/dashboard/$guildId/commands", cta: "Manage commands", icon: FileText },
  { title: "Tickets", body: "Support workflow, panels and open conversations.", to: "/dashboard/$guildId/tickets", cta: "Open tickets", icon: Ticket },
  { title: "Activity", body: "Recent events and operational activity.", to: "/dashboard/$guildId/activity", cta: "View activity", icon: Activity },
  { title: "General settings", body: "Core server defaults and bot configuration.", to: "/dashboard/$guildId/general", cta: "Open settings", icon: Gauge },
] as const;

function GuildHome() {
  const { guildId, config, overview } = useGuild();
  const name = config?.guild.name;
  const icon = config?.guild.icon ? `https://cdn.discordapp.com/icons/${guildId}/${config.guild.icon}.png?size=128` : null;
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[32px] border border-primary/20 bg-gradient-to-br from-primary/15 via-card/80 to-transparent p-5 shadow-[0_30px_100px_rgba(0,0,0,.3)] backdrop-blur-2xl sm:p-8"><div aria-hidden className="absolute -right-24 -top-24 size-80 rounded-full bg-primary/10 blur-3xl" /><div aria-hidden className="absolute bottom-0 left-1/3 h-32 w-64 rounded-full bg-cyan-400/5 blur-3xl" /><div className="relative flex flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-start gap-4"><div className="relative shrink-0">{icon ? <img src={icon} alt={`${name ?? "Server"} icon`} className="size-20 rounded-3xl object-cover ring-1 ring-primary/30 shadow-2xl sm:size-24" /> : <span className="flex size-20 items-center justify-center rounded-3xl bg-secondary text-2xl font-black sm:size-24">{(name ?? "AH").slice(0, 2).toUpperCase()}</span>}<span className={`absolute -bottom-1 -right-1 flex size-5 items-center justify-center rounded-full border-4 border-card ${overview?.botPresent ? "bg-emerald-400" : "bg-red-400"}`} aria-label={overview?.botPresent ? "Bot online" : "Bot offline"} /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="border-primary/40 text-primary"><Sparkles className="mr-1 size-3" />Server Command Center</Badge>{overview?.botPresent ? <Badge variant="outline" className="border-emerald-500/30 text-emerald-300"><Bot className="mr-1 size-3" />!HOY online</Badge> : null}</div><h1 className="mt-3 truncate text-3xl font-black tracking-tight sm:text-4xl">{name ?? "Server Dashboard"}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">A premium operations surface for moderation, support, automation, analytics and your community's daily activity.</p></div></div><div className="flex flex-wrap gap-2"><Button asChild className="gap-2"><Link to="/statahoy/$guildId" params={{ guildId }}><BarChart3 className="size-4" />View analytics</Link></Button><Button asChild variant="outline" className="gap-2"><Link to="/dashboard/$guildId/general" params={{ guildId }}><Gauge className="size-4" />Server settings</Link></Button></div></div></section>

    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{!overview ? [0,1,2,3].map((i) => <Skeleton key={i} className="h-32 rounded-2xl" />) : <><MetricLink icon={Users} label="Members" value={overview.memberCount ?? "—"} detail="Current server population" to="/dashboard/$guildId/roles" guildId={guildId} /><MetricLink icon={Ticket} label="Open tickets" value={overview.openTickets} detail="Open ticket conversations" to="/dashboard/$guildId/tickets" guildId={guildId} /><MetricLink icon={ShieldAlert} label="Active warnings" value={overview.activeWarnings} detail="Members with active warnings" to="/dashboard/$guildId/moderation" guildId={guildId} /><MetricLink icon={Activity} label="Moderation · 7d" value={overview.moderationLast7Days} detail="Actions recorded this week" to="/dashboard/$guildId/moderation" guildId={guildId} /></>}</div>

    {overview ? <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Server health"><Health label="Bot status" value={overview.botPresent ? "Online" : "Not installed"} good={overview.botPresent} icon={Bot} /><Health label="Channels" value={overview.channels} good icon={MessageSquare} /><Health label="Roles" value={overview.roles} good icon={Users} /><Health label="Tracked members" value={overview.trackedMembers} good icon={Activity} /></section> : null}

    <section aria-labelledby="modules-title"><div className="flex items-end justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[.25em] text-primary">Operations</p><h2 id="modules-title" className="mt-1 text-2xl font-black">Your server tools</h2><p className="mt-1 text-sm text-muted-foreground">Everything is organized into focused command-center modules.</p></div><Badge variant="secondary">{QUICK.length} modules</Badge></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{QUICK.map((card) => <Card key={card.title} className="group overflow-hidden border-white/[0.1] bg-white/[0.035] shadow-[0_18px_60px_rgba(0,0,0,.16)] backdrop-blur-xl transition hover:-translate-y-1 hover:border-primary/30"><CardContent className="p-5"><div className="flex items-start justify-between"><span className="flex size-11 items-center justify-center rounded-2xl border border-primary/15 bg-primary/10 text-primary"><card.icon className="size-5" /></span><ArrowRight className="size-4 text-white/20 transition group-hover:translate-x-1 group-hover:text-primary" /></div><h3 className="mt-5 text-lg font-bold">{card.title}</h3><p className="mt-1 min-h-12 text-sm leading-6 text-muted-foreground">{card.body}</p><Button asChild size="sm" variant="secondary" className="mt-4 gap-1"><Link to={card.to} params={{ guildId }}>{card.cta}<ArrowRight className="size-3.5" /></Link></Button></CardContent></Card>)}</div></section>

    <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-white/[0.1] bg-white/[0.03] p-5 shadow-xl backdrop-blur-xl sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[.25em] text-primary">Recent activity</p><h2 className="mt-1 text-lg font-bold">Moderation timeline</h2></div><Button asChild size="sm" variant="ghost" className="gap-1"><Link to="/dashboard/$guildId/moderation" params={{ guildId }}>View all <ArrowRight className="size-3.5" /></Link></Button></div>{overview && overview.recent.length ? <ul className="mt-5 space-y-2">{overview.recent.map((entry, index) => <li key={`${entry.created_at}-${index}`} className="flex flex-wrap items-center gap-3 rounded-2xl border border-white/[0.08] bg-black/15 px-4 py-3 text-sm"><Badge variant="outline" className="border-primary/30 text-primary">{entry.action}</Badge><span className="font-medium">{entry.target_name ?? "Unknown"}</span><span className="text-muted-foreground">by {entry.moderator_name ?? "!HOY BOT"}</span><span className="ml-auto text-xs text-muted-foreground">{new Date(entry.created_at).toLocaleString()}</span></li>)}</ul> : <p className="mt-5 rounded-2xl border border-dashed border-white/10 p-7 text-center text-sm text-muted-foreground">No moderation actions recorded yet.</p>}</div><div className="rounded-3xl border border-primary/15 bg-primary/[0.045] p-5 shadow-xl backdrop-blur-xl sm:p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl border border-primary/20 bg-primary/10 text-primary"><CalendarDays className="size-5" /></span><div><p className="text-[9px] font-bold uppercase tracking-[.25em] text-primary">Analytics</p><h2 className="font-bold">Statahoy intelligence</h2></div></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Open the unified analytics workspace for server statistics, ranks, member profiles, messages, voice and activity.</p><Button asChild className="mt-5 w-full gap-2"><Link to="/statahoy/$guildId" params={{ guildId }}>Open Statahoy <ArrowRight className="size-4" /></Link></Button></div></section>
  </div>;
}

function MetricLink({ icon: Icon, label, value, detail, to, guildId }: { icon: typeof Users; label: string; value: string | number; detail: string; to: string; guildId: string }) { return <Link to={to} params={{ guildId }} aria-label={`${label}: ${value}. Open ${label.toLowerCase()} management`} className="group block rounded-2xl border border-white/[0.1] bg-white/[0.035] shadow-[0_15px_50px_rgba(0,0,0,.16)] backdrop-blur-xl transition hover:-translate-y-0.5 hover:border-primary/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><CardContent className="p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-white/40">{label}</p><Icon className="size-4 text-primary transition group-hover:scale-110" /></div><p className="mt-3 text-3xl font-black tracking-tight">{typeof value === "number" ? value.toLocaleString() : value}</p><p className="mt-1 text-xs text-white/35">{detail}</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-[.14em] text-primary/70">Open module <span aria-hidden>→</span></p></CardContent></Link>; }
function Health({ label, value, good, icon: Icon }: { label: string; value: string | number; good: boolean; icon: typeof Bot }) { return <div className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-4 backdrop-blur-xl"><div className="flex items-center gap-2"><Icon className="size-4 text-primary" /><span className="text-xs uppercase tracking-[.14em] text-muted-foreground">{label}</span></div><div className="mt-2 flex items-center gap-2"><span className="font-semibold">{value}</span><span className={`size-2 rounded-full ${good ? "bg-emerald-400" : "bg-red-400"}`} aria-label={good ? "Healthy" : "Unavailable"} /></div></div>; }
