import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Field, PickerSelect, SectionHeader, ToggleRow } from "./fields";
import { SaveBar } from "./save-bar";
import type { PanelProps } from "./types";
import { useDraft } from "./use-draft";
export function AdvancedGeneralPanel({ guildId, config, onSaved }: PanelProps) {
 const s=config.settings; const channels=config.structure.channels.filter(c=>c.kind==="text"); const categories=config.structure.channels.filter(c=>c.kind==="category");
 const form=useDraft(guildId,"general",{prefix:s?.prefix??"!",currency_name:s?.currency_name??"Coins",currency_symbol:s?.currency_symbol??"🪙",timezone:s?.timezone??"UTC",mod_log_channel_id:s?.mod_log_channel_id??null,economy_enabled:s?.economy_enabled??true,daily_reward:s?.daily_reward??250,starting_balance:s?.starting_balance??100,tickets_enabled:s?.tickets_enabled??true,ticket_category_id:s?.ticket_category_id??null,ticket_panel_channel_id:s?.ticket_panel_channel_id??null,ticket_support_role_ids:s?.ticket_support_role_ids??[],ticket_welcome_message:s?.ticket_welcome_message??"Ahoy! A crew member will be with you shortly. ⚓",ticket_transcripts_enabled:s?.ticket_transcripts_enabled??true,ticket_transcript_channel_id:s?.ticket_transcript_channel_id??null,ticket_dm_transcript_enabled:s?.ticket_dm_transcript_enabled??false},onSaved);
 const {draft,set,dirty,saving,save,reset}=form;
 return <div className="space-y-6"><Card className="glass border-0"><CardContent className="space-y-5 pt-6"><SectionHeader title="Core Settings" description="Prefix, currency, timezone and moderation routing."/><div className="grid gap-5 md:grid-cols-2"><Field label="Legacy prefix"><Input maxLength={5} value={draft.prefix} onChange={e=>set("prefix",e.target.value)}/></Field><Field label="Timezone"><Input value={draft.timezone} onChange={e=>set("timezone",e.target.value)}/></Field><Field label="Currency name"><Input value={draft.currency_name} onChange={e=>set("currency_name",e.target.value)}/></Field><Field label="Currency symbol"><Input value={draft.currency_symbol} onChange={e=>set("currency_symbol",e.target.value)}/></Field><Field label="Moderation log channel"><PickerSelect value={draft.mod_log_channel_id} options={channels} onChange={v=>set("mod_log_channel_id",v)} placeholder="Select a channel"/></Field></div></CardContent></Card>
 <Card className="glass border-0"><CardContent className="space-y-5 pt-6"><SectionHeader title="Economy" description="Daily rewards and starting balances."/><ToggleRow label="Enable economy" checked={draft.economy_enabled} onChange={v=>set("economy_enabled",v)}/><div className="grid gap-5 md:grid-cols-2"><Field label="Daily reward"><Input type="number" min={0} max={1000000} value={draft.daily_reward} onChange={e=>set("daily_reward",Number(e.target.value)||0)}/></Field><Field label="Starting balance"><Input type="number" min={0} max={1000000} value={draft.starting_balance} onChange={e=>set("starting_balance",Number(e.target.value)||0)}/></Field></div></CardContent></Card>
 <Card className="glass border-0"><CardContent className="space-y-5 pt-6"><SectionHeader title="Tickets" description="Private support tickets, routing and transcript delivery."/><ToggleRow label="Enable tickets" checked={draft.tickets_enabled} onChange={v=>set("tickets_enabled",v)}/><div className="grid gap-5 md:grid-cols-2"><Field label="Default ticket category"><PickerSelect value={draft.ticket_category_id} options={categories} onChange={v=>set("ticket_category_id",v)} placeholder="Select a category"/></Field><Field label="Panel channel"><PickerSelect value={draft.ticket_panel_channel_id} options={channels} onChange={v=>set("ticket_panel_channel_id",v)} placeholder="Select a channel"/></Field></div><Field label="Ticket welcome message"><Input value={draft.ticket_welcome_message} onChange={e=>set("ticket_welcome_message",e.target.value)}/></Field><ToggleRow label="Save transcripts" checked={draft.ticket_transcripts_enabled} onChange={v=>set("ticket_transcripts_enabled",v)}/><Field label="Transcript channel"><PickerSelect value={draft.ticket_transcript_channel_id} options={channels} onChange={v=>set("ticket_transcript_channel_id",v)} placeholder="Not set"/></Field><ToggleRow label="DM transcript to ticket owner" checked={draft.ticket_dm_transcript_enabled} onChange={v=>set("ticket_dm_transcript_enabled",v)}/></CardContent></Card><SaveBar dirty={dirty} saving={saving} onSave={save} onReset={reset}/></div>;
}
