import { useMutation, useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Eye, Gem, Play, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { getCardSettings, saveCardSettings } from "@/lib/card-settings.functions";
import { testSend, testWelcome, testXp } from "@/lib/feature-test.functions";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ToggleRow } from "./fields";
const styles=[{value:"glassmorphism",label:"Glassmorphism"},{value:"gold",label:"Gold Edition"},{value:"minimal",label:"Minimal"}] as const;
export function CinematicCardStudio({guildId}:{guildId:string}){
 const q=useQuery({queryKey:["card-settings",guildId],queryFn:()=>getCardSettings({data:{guildId}})}); const save=useServerFn(saveCardSettings); const m=useMutation({mutationFn:(values:Record<string,unknown>)=>save({data:{guildId,values}}),onSuccess:()=>{toast.success("Cinematic card settings saved");void q.refetch()},onError:(e:Error)=>toast.error(e.message)}); const s=q.data as any; if(!s)return null; const patch=(k:string,v:unknown)=>m.mutate({[k]:v});
 return <Card className="glass border-0 overflow-hidden"><CardContent className="space-y-6 pt-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Gem className="size-5 text-primary"/><h2 className="text-lg font-bold">Cinematic Card Studio</h2></div><p className="mt-1 text-sm text-muted-foreground">One premium visual system for XP, level-up, welcome and profile cards.</p></div><span className="rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-[10px] uppercase tracking-widest text-primary">Live</span></div>
 <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-primary/20 bg-black/20 p-4 space-y-4"><div><p className="font-semibold">XP & Level-up</p><p className="text-xs text-muted-foreground">Every message awards the configured XP. No countdown cooldown.</p></div><ToggleRow label="Enable XP rank card" checked={s.xp_card_enabled} onChange={v=>patch("xp_card_enabled",v)}/><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-xs">XP style<Select value={s.xp_card_style} onValueChange={v=>patch("xp_card_style",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{styles.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></label><label className="space-y-1 text-xs">Level-up style<Select value={s.level_up_card_style} onValueChange={v=>patch("level_up_card_style",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{styles.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></label></div><div className="grid gap-2 sm:grid-cols-2"><ToggleRow label="Show progress" checked={s.xp_card_show_progress} onChange={v=>patch("xp_card_show_progress",v)}/><ToggleRow label="Show rank" checked={s.xp_card_show_rank} onChange={v=>patch("xp_card_show_rank",v)}/><ToggleRow label="Show stats" checked={s.xp_card_show_stats} onChange={v=>patch("xp_card_show_stats",v)}/><ToggleRow label="Show total XP" checked={s.xp_card_show_total_xp} onChange={v=>patch("xp_card_show_total_xp",v)}/><ToggleRow label="Enable level-up card" checked={s.level_up_card_enabled} onChange={v=>patch("level_up_card_enabled",v)}/><ToggleRow label="Level-up progress" checked={s.level_up_card_show_progress} onChange={v=>patch("level_up_card_show_progress",v)}/><ToggleRow label="Level-up rank" checked={s.level_up_card_show_rank} onChange={v=>patch("level_up_card_show_rank",v)}/></div></section>
 <section className="rounded-2xl border border-white/10 bg-black/20 p-4 space-y-4"><div><p className="font-semibold">Welcomer & Profile</p><p className="text-xs text-muted-foreground">Keep every member-facing card visually consistent.</p></div><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-xs">Welcome style<Select value={s.welcome_card_style} onValueChange={v=>patch("welcome_card_style",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{styles.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></label><label className="space-y-1 text-xs">Profile style<Select value={s.profile_card_style} onValueChange={v=>patch("profile_card_style",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{styles.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></label></div><div className="rounded-xl border border-primary/10 bg-primary/[0.04] p-4"><div className="flex items-center gap-2 text-primary"><Sparkles className="size-4"/><span className="text-sm font-semibold">Cinematic preview</span></div><div className="mt-3 rounded-xl border border-white/10 bg-[#07131d]/90 p-4 shadow-[0_0_30px_rgba(31,182,166,.08)]"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-widest text-primary">LEVEL UP</span><span className="text-xs text-white/40">{s.level_up_card_style}</span></div><p className="mt-2 font-semibold">⚓ Crew member reached the next level</p><p className="mt-1 text-xs text-white/45">Progress and rank visibility follow your toggles.</p><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-2 w-3/4 rounded-full bg-primary shadow-[0_0_14px_rgba(31,182,166,.45)]"/></div></div></div><Button variant="outline" className="w-full" onClick={()=>void q.refetch()}><Eye className="mr-2 size-4"/>Refresh preview</Button></section></div>
 </CardContent></Card>;
}
export function FeatureTestStudio({guildId,channelId}:{guildId:string;channelId:string}){
 const runSend=useServerFn(testSend),runWelcome=useServerFn(testWelcome),runXp=useServerFn(testXp); const m=useMutation({mutationFn:async(kind:"welcome"|"send"|"xp")=>kind==="welcome"?runWelcome({data:{guildId,channelId}}):kind==="send"?runSend({data:{guildId,channelId,message:"This is a live Send test from the !HOY BOT control center. ⚓"}}):runXp({data:{guildId,channelId}}),onSuccess:()=>toast.success("Test delivered to Discord"),onError:(e:Error)=>toast.error(e.message)});
 return <Card className="glass border-0"><CardContent className="space-y-4 pt-6"><div><div className="flex items-center gap-2"><Play className="size-5 text-primary"/><h2 className="text-lg font-bold">Test Features</h2></div><p className="mt-1 text-sm text-muted-foreground">Send a real test into the selected Discord channel before publishing changes.</p></div><div className="grid gap-3 sm:grid-cols-3">{[["welcome","Welcome"],["send","Send"],["xp","XP & Leveling"]].map(([kind,label])=><Button key={kind} variant="outline" disabled={m.isPending} onClick={()=>m.mutate(kind as any)}>{label}</Button>)}</div></CardContent></Card>;
}
