import { useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Crown, Minus, Plus, Shield, TrendingUp } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { adminXpAction } from "@/lib/xp-admin.functions";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
export function XPAdminPanel({guildId}:{guildId:string}){const[action,setAction]=useState("give");const[targets,setTargets]=useState("");const[amount,setAmount]=useState("100");const[role,setRole]=useState("");const run=useServerFn(adminXpAction);const m=useMutation({mutationFn:()=>run({data:{guildId,action:action as any,targets,amount:action.includes("rank")?undefined:Number(amount),role:action.includes("rank")?role:undefined}}),onSuccess:r=>{toast.success(`Action applied to ${r.count} user(s)`);setTargets("")},onError:(e:Error)=>toast.error(e.message)});return <Card className="glass border-0"><CardContent className="space-y-5 pt-6"><div className="flex items-start gap-3"><span className="flex size-11 items-center justify-center rounded-2xl border border-primary/20 bg-primary/10 text-primary"><Crown/></span><div><h2 className="text-lg font-bold">XP & Rank Command Deck</h2><p className="text-sm text-muted-foreground">Run the same privileged controls available in Discord, including bulk username targeting.</p></div></div><div className="grid gap-4 lg:grid-cols-[220px_1fr_180px]"><label className="space-y-1 text-xs">Action<Select value={action} onValueChange={setAction}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="give"><Plus className="mr-2 inline size-3"/>Give XP</SelectItem><SelectItem value="remove"><Minus className="mr-2 inline size-3"/>Remove XP</SelectItem><SelectItem value="level-up"><TrendingUp className="mr-2 inline size-3"/>Level up</SelectItem><SelectItem value="rank-give"><Shield className="mr-2 inline size-3"/>Give rank role</SelectItem><SelectItem value="rank-remove"><Shield className="mr-2 inline size-3"/>Remove rank role</SelectItem></SelectContent></Select></label><label className="space-y-1 text-xs">Target usernames / IDs<Input value={targets} onChange={e=>setTargets(e.target.value)} placeholder="username1, username2, @member or ID"/></label>{action.includes("rank")?<label className="space-y-1 text-xs">Role name<Input value={role} onChange={e=>setRole(e.target.value)} placeholder="Crew rank"/></label>:action!=="level-up"?<label className="space-y-1 text-xs">XP amount<Input type="number" min={1} value={amount} onChange={e=>setAmount(e.target.value)}/></label>:<div/>}</div><div className="flex flex-col gap-3 rounded-2xl border border-primary/10 bg-primary/[.04] p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-muted-foreground">Bulk targets are comma-separated; actions are logged to the dashboard access audit trail.</p><Button disabled={!targets.trim()||m.isPending} onClick={()=>m.mutate()}>{m.isPending?"Executing…":"Execute command"}</Button></div></CardContent></Card>}
