/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. Keep the runtime route tree in sync with src/routes.
// Lovable preview build recovery: keep the generated route tree checked in so the SSR worker
// always has a concrete route-tree module available during preview bundling.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OwnerConsoleRouteImport } from './routes/owner-console'
import { Route as OwnerConsolePlanRequestsRouteImport } from './routes/owner-console.plan-requests'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppealGuildIdRouteImport } from './routes/appeal/$guildId'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as CalendarGuildIdRouteImport } from './routes/calendar/$guildId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard/$guildId'
import { Route as StatahoyIndexRouteImport } from './routes/statahoy/index'
import { Route as StatahoyGuildIdRouteImport } from './routes/statahoy/$guildId'
import { Route as StatahoyGuildIdActivityRouteImport } from './routes/statahoy/$guildId.activity'
import { Route as ApiPublicInviteRouteImport } from './routes/api/public/invite'
import { Route as DashboardGuildIdIndexRouteImport } from './routes/dashboard/$guildId.index'
import { Route as DashboardGuildIdActivityRouteImport } from './routes/dashboard/$guildId.activity'
import { Route as DashboardGuildIdAutomationRouteImport } from './routes/dashboard/$guildId.automation'
import { Route as DashboardGuildIdAutomodRouteImport } from './routes/dashboard/$guildId.automod'
import { Route as DashboardGuildIdCalendarRouteImport } from './routes/dashboard/$guildId.calendar'
import { Route as DashboardGuildIdCommandsRouteImport } from './routes/dashboard/$guildId.commands'
import { Route as DashboardGuildIdCommunityRouteImport } from './routes/dashboard/$guildId.community'
import { Route as DashboardGuildIdCustomCommandsRouteImport } from './routes/dashboard/$guildId.custom-commands'
import { Route as DashboardGuildIdEngagementRouteImport } from './routes/dashboard/$guildId.engagement'
import { Route as DashboardGuildIdErrorsRouteImport } from './routes/dashboard/$guildId.errors'
import { Route as DashboardGuildIdGeneralRouteImport } from './routes/dashboard/$guildId.general'
import { Route as DashboardGuildIdLoggingRouteImport } from './routes/dashboard/$guildId.logging'
import { Route as DashboardGuildIdModerationRouteImport } from './routes/dashboard/$guildId.moderation'
import { Route as DashboardGuildIdRolesRouteImport } from './routes/dashboard/$guildId.roles'
import { Route as DashboardGuildIdRollCallRouteImport } from './routes/dashboard/$guildId.rollcall'
import { Route as DashboardGuildIdSendRouteImport } from './routes/dashboard/$guildId.send'
import { Route as DashboardGuildIdStatsRouteImport } from './routes/dashboard/$guildId.stats'
import { Route as DashboardGuildIdWelcomeRouteImport } from './routes/dashboard/$guildId.welcome'
import { Route as ApiPublicHooksCalendarSyncRouteImport } from './routes/api/public/hooks/calendar-sync'
import { Route as ApiPublicMediaFileNameRouteImport } from './routes/api/public/media/$fileName'
import { Route as ApiPublicMediaUploadRouteImport } from './routes/api/public/media/upload'
import { Route as DashboardGuildIdEventEventIdRouteImport } from './routes/dashboard/$guildId.event.$eventId'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord/callback'
import { Route as ApiPublicAuthDiscordLogoutRouteImport } from './routes/api/public/auth/discord/logout'
import { Route as ApiPublicAuthDiscordStartRouteImport } from './routes/api/public/auth/discord/start'
import { Route as ApiPublicAuthGoogleCallbackRouteImport } from './routes/api/public/auth/google/callback'
import { Route as ApiPublicAuthGoogleStartRouteImport } from './routes/api/public/auth/google/start'

const make = (route: any, id: string, path: string, parent: any) => route.update({ id, path, getParentRoute: () => parent } as any)
const IndexRoute = make(IndexRouteImport, '/', '/', rootRouteImport)
const SplatRoute = make(SplatRouteImport, '/$', '/$', rootRouteImport)
const AdminRoute = make(AdminRouteImport, '/admin', '/admin', rootRouteImport)
const OwnerConsoleRoute = make(OwnerConsoleRouteImport, '/owner-console', '/owner-console', rootRouteImport)
const OwnerConsolePlanRequestsRoute = make(OwnerConsolePlanRequestsRouteImport, '/owner-console/plan-requests', '/owner-console/plan-requests', rootRouteImport)
const PricingRoute = make(PricingRouteImport, '/pricing', '/pricing', rootRouteImport)
const AppealGuildIdRoute = make(AppealGuildIdRouteImport, '/appeal/$guildId', '/appeal/$guildId', rootRouteImport)
const CalendarIndexRoute = make(CalendarIndexRouteImport, '/calendar/', '/calendar/', rootRouteImport)
const CalendarGuildIdRoute = make(CalendarGuildIdRouteImport, '/calendar/$guildId', '/calendar/$guildId', rootRouteImport)
const DashboardIndexRoute = make(DashboardIndexRouteImport, '/dashboard/', '/dashboard/', rootRouteImport)
const DashboardGuildIdRoute = make(DashboardGuildIdRouteImport, '/dashboard/$guildId', '/dashboard/$guildId', rootRouteImport)
const StatahoyIndexRoute = make(StatahoyIndexRouteImport, '/statahoy/', '/statahoy/', rootRouteImport)
const StatahoyGuildIdRoute = make(StatahoyGuildIdRouteImport, '/statahoy/$guildId', '/statahoy/$guildId', rootRouteImport)
const StatahoyGuildIdActivityRoute = make(StatahoyGuildIdActivityRouteImport, '/activity', '/activity', StatahoyGuildIdRoute)
const ApiPublicInviteRoute = make(ApiPublicInviteRouteImport, '/api/public/invite', '/api/public/invite', rootRouteImport)
const DashboardGuildIdIndexRoute = make(DashboardGuildIdIndexRouteImport, '/', '/', DashboardGuildIdRoute)
const DashboardGuildIdActivityRoute = make(DashboardGuildIdActivityRouteImport, '/activity', '/activity', DashboardGuildIdRoute)
const DashboardGuildIdAutomationRoute = make(DashboardGuildIdAutomationRouteImport, '/automation', '/automation', DashboardGuildIdRoute)
const DashboardGuildIdAutomodRoute = make(DashboardGuildIdAutomodRouteImport, '/automod', '/automod', DashboardGuildIdRoute)
const DashboardGuildIdCalendarRoute = make(DashboardGuildIdCalendarRouteImport, '/calendar', '/calendar', DashboardGuildIdRoute)
const DashboardGuildIdCommandsRoute = make(DashboardGuildIdCommandsRouteImport, '/commands', '/commands', DashboardGuildIdRoute)
const DashboardGuildIdCommunityRoute = make(DashboardGuildIdCommunityRouteImport, '/community', '/community', DashboardGuildIdRoute)
const DashboardGuildIdCustomCommandsRoute = make(DashboardGuildIdCustomCommandsRouteImport, '/custom-commands', '/custom-commands', DashboardGuildIdRoute)
const DashboardGuildIdEngagementRoute = make(DashboardGuildIdEngagementRouteImport, '/engagement', '/engagement', DashboardGuildIdRoute)
const DashboardGuildIdErrorsRoute = make(DashboardGuildIdErrorsRouteImport, '/errors', '/errors', DashboardGuildIdRoute)
const DashboardGuildIdGeneralRoute = make(DashboardGuildIdGeneralRouteImport, '/general', '/general', DashboardGuildIdRoute)
const DashboardGuildIdLoggingRoute = make(DashboardGuildIdLoggingRouteImport, '/logging', '/logging', DashboardGuildIdRoute)
const DashboardGuildIdModerationRoute = make(DashboardGuildIdModerationRouteImport, '/moderation', '/moderation', DashboardGuildIdRoute)
const DashboardGuildIdRolesRoute = make(DashboardGuildIdRolesRouteImport, '/roles', '/roles', DashboardGuildIdRoute)
const DashboardGuildIdRollCallRoute = make(DashboardGuildIdRollCallRouteImport, '/rollcall', '/rollcall', DashboardGuildIdRoute)
const DashboardGuildIdSendRoute = make(DashboardGuildIdSendRouteImport, '/send', '/send', DashboardGuildIdRoute)
const DashboardGuildIdStatsRoute = make(DashboardGuildIdStatsRouteImport, '/stats', '/stats', DashboardGuildIdRoute)
const DashboardGuildIdWelcomeRoute = make(DashboardGuildIdWelcomeRouteImport, '/welcome', '/welcome', DashboardGuildIdRoute)
const ApiPublicHooksCalendarSyncRoute = make(ApiPublicHooksCalendarSyncRouteImport, '/api/public/hooks/calendar-sync', '/api/public/hooks/calendar-sync', rootRouteImport)
const ApiPublicMediaFileNameRoute = make(ApiPublicMediaFileNameRouteImport, '/api/public/media/$fileName', '/api/public/media/$fileName', rootRouteImport)
const ApiPublicMediaUploadRoute = make(ApiPublicMediaUploadRouteImport, '/api/public/media/upload', '/api/public/media/upload', rootRouteImport)
const DashboardGuildIdEventEventIdRoute = make(DashboardGuildIdEventEventIdRouteImport, '/event/$eventId', '/event/$eventId', DashboardGuildIdRoute)
const ApiPublicAuthDiscordCallbackRoute = make(ApiPublicAuthDiscordCallbackRouteImport, '/api/public/auth/discord/callback', '/api/public/auth/discord/callback', rootRouteImport)
const ApiPublicAuthDiscordLogoutRoute = make(ApiPublicAuthDiscordLogoutRouteImport, '/api/public/auth/discord/logout', '/api/public/auth/discord/logout', rootRouteImport)
const ApiPublicAuthDiscordStartRoute = make(ApiPublicAuthDiscordStartRouteImport, '/api/public/auth/discord/start', '/api/public/auth/discord/start', rootRouteImport)
const ApiPublicAuthGoogleCallbackRoute = make(ApiPublicAuthGoogleCallbackRouteImport, '/api/public/auth/google/callback', '/api/public/auth/google/callback', rootRouteImport)
const ApiPublicAuthGoogleStartRoute = make(ApiPublicAuthGoogleStartRouteImport, '/api/public/auth/google/start', '/api/public/auth/google/start', rootRouteImport)

const DashboardGuildIdRouteWithChildren = DashboardGuildIdRoute._addFileChildren({ DashboardGuildIdActivityRoute, DashboardGuildIdAutomationRoute, DashboardGuildIdAutomodRoute, DashboardGuildIdCalendarRoute, DashboardGuildIdCommandsRoute, DashboardGuildIdCommunityRoute, DashboardGuildIdCustomCommandsRoute, DashboardGuildIdEngagementRoute, DashboardGuildIdErrorsRoute, DashboardGuildIdGeneralRoute, DashboardGuildIdLoggingRoute, DashboardGuildIdModerationRoute, DashboardGuildIdRolesRoute, DashboardGuildIdRollCallRoute, DashboardGuildIdSendRoute, DashboardGuildIdStatsRoute, DashboardGuildIdWelcomeRoute, DashboardGuildIdIndexRoute, DashboardGuildIdEventEventIdRoute })
const StatahoyGuildIdRouteWithChildren = StatahoyGuildIdRoute._addFileChildren({ StatahoyGuildIdActivityRoute })

const rootRouteChildren = { IndexRoute, SplatRoute, AdminRoute, OwnerConsoleRoute, OwnerConsolePlanRequestsRoute, PricingRoute, AppealGuildIdRoute, CalendarGuildIdRoute, DashboardGuildIdRoute: DashboardGuildIdRouteWithChildren, StatahoyGuildIdRoute: StatahoyGuildIdRouteWithChildren, CalendarIndexRoute, DashboardIndexRoute, StatahoyIndexRoute, ApiPublicInviteRoute, ApiPublicHooksCalendarSyncRoute, ApiPublicMediaFileNameRoute, ApiPublicMediaUploadRoute, ApiPublicAuthDiscordCallbackRoute, ApiPublicAuthDiscordLogoutRoute, ApiPublicAuthDiscordStartRoute, ApiPublicAuthGoogleCallbackRoute, ApiPublicAuthGoogleStartRoute }

export interface FileRoutesByFullPath { [key: string]: any }
export interface FileRoutesByTo { [key: string]: any }
export interface FileRouteTypes { fileRoutesByFullPath: FileRoutesByFullPath; fullPaths: string; fileRoutesByTo: FileRoutesByTo; id: string; fileRoutesById: FileRoutesById }
declare module '@tanstack/react-router' { interface FileRoutesByPath { [key: string]: any } }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> } }
