// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://wwluqfjwcfpvjjubqbky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3bHVxZmp3Y2ZwdmpqdWJxYmt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3NDgzNDQsImV4cCI6MjEwMjMyNDM0NH0.CUwSIROoL0retlJWrjr1mxi8J5H-qLdIiAOKCXKe7p8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});